### ISSUE TITLE
Setup Relay

### ISSUE THREAD

**Issue by manyaagarwal** [MLH-Fellowship/0.4.1-Reader#7]

**Comment by taneliang** [comment]
Discussed with @manyaagarwal offline. Reassigning this to me as it'll be more seamless if I set up both Amplify (#1) and Relay together.

**Comment by manyaagarwal** [comment]
Yes, agreed!

**Comment by manyaagarwal** [comment]
Pull Request #12 adds the environment and schema files to the project. The basic structure to use Relay is now in place. This should unblock the further development of the project.
